### ISSUE TITLE
system tests: "Failed to find socket within 10 seconds (Kurma::Error)" on startup

### ISSUE THREAD

**Issue by alextoombs** [apcera/kurma#126]
Occasionally, system tests fail with this error on initialization of Kurma:

```
[18:54:04][vagrant] /opt/ruby/bin/ruby -I/opt/ruby/lib/ruby/gems/2.2.0/gems/rspec-core-3.1.7/lib:/opt/ruby/lib/ruby/gems/2.2.0/gems/rspec-support-3.1.2/lib /opt/ruby/lib/ruby/gems/2.2.0/gems/rspec-core-3.1.7/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb --format RSpec::Instafail --format JUnit -o log/test_report.xml --color
[18:54:20][vagrant] /checkout/src/github.com/apcera/kurma/testing/integration/lib/kurma/server.rb:98:in `block in wait_for_socket': Failed to find socket within 10 seconds (Kurma::Error)
[18:54:20][vagrant] 	from /checkout/src/github.com/apcera/kurma/testing/integration/lib/kurma/server.rb:95:in `loop'
[18:54:20][vagrant] 	from /checkout/src/github.com/apcera/kurma/testing/integration/lib/kurma/server.rb:95:in `wait_for_socket'
[18:54:20][vagrant] 	from /checkout/src/github.com/apcera/kurma/testing/integration/lib/kurma/server.rb:71:in `start'
[18:54:20][vagrant] 	from /checkout/src/github.com/apcera/kurma/testing/integration/spec/spec_helper.rb:29:in `block (2 levels) in <top (required)>'
[18:54:20][vagrant] 	from /opt/ruby/lib/ruby/gems/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/example.rb:322:in `instance_exec'
[18:54:20][vagrant] 	from /opt/ruby/lib/ruby/gems/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/example.rb:322:in `instance_exec'
[18:54:20][vagrant] 	from /opt/ruby/lib/ruby/gems/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/hooks.rb:350:in `run'
[18:54:20][vagrant] 	from /opt/ruby/lib/ruby/gems/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/hooks.rb:427:in `block in run'
[18:54:20][vagrant] 	from /opt/ruby/lib/ruby/gems/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/hooks.rb:427:in `each'
[18:54:20][vagrant] 	from /opt/ruby/lib/ruby/gems/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/hooks.rb:427:in `run'
[18:54:20][vagrant] 	from /opt/ruby/lib/ruby/gems/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/hooks.rb:500:in `run'
[18:54:20][vagrant] 	from /opt/ruby/lib/ruby/gems/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:110:in `block in run_specs'
[18:54:20][vagrant] 	from /opt/ruby/lib/ruby/gems/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/reporter.rb:53:in `report'
[18:54:20][vagrant] 	from /opt/ruby/lib/ruby/gems/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:107:in `run_specs'
[18:54:20][vagrant] 	from /opt/ruby/lib/ruby/gems/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:85:in `run'
[18:54:20][vagrant] 	from /opt/ruby/lib/ruby/gems/2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:69:in `run'
```

From [this build in CI](http://ci.kurma.io/viewLog.html?buildId=18461).

**Comment by krobertson** [comment]
The kurmad logs:

```
2016-08-25 18:54:06.448659836 +0000 UTC [DEBUG pid=1088 pod='' source='runner.go:161'] Fetched image "file:////checkout/src/github.com/apcera/kurma/testing/integration/lib/kurma/../../../../bin/busybox.aci"
2016-08-25 18:54:06.957351925 +0000 UTC [TRACE pid=1088 pod='' source='runner.go:207'] Pod Manager has been initialized.
2016-08-25 18:54:09.746553312 +0000 UTC [DEBUG pid=1088 pod='89851f65-fd69-4e10-94ee-4cc5b4f3dc3e' source='manager.go:207'] Launching pod "kurma-networking"
2016-08-25 18:54:09.746586515 +0000 UTC [DEBUG pid=1088 pod='89851f65-fd69-4e10-94ee-4cc5b4f3dc3e' source='pod_operations.go:99'] Setting up directories.
2016-08-25 18:54:09.746676042 +0000 UTC [DEBUG pid=1088 pod='89851f65-fd69-4e10-94ee-4cc5b4f3dc3e' source='pod_operations.go:111'] Done setting up directories.
2016-08-25 18:54:09.746714090 +0000 UTC [DEBUG pid=1088 pod='89851f65-fd69-4e10-94ee-4cc5b4f3dc3e' source='pod_operations.go:171'] Skipping stager network configuration
2016-08-25 18:54:09.746793078 +0000 UTC [DEBUG pid=1088 pod='89851f65-fd69-4e10-94ee-4cc5b4f3dc3e' source='pod_operations.go:248'] Initializing the container for the stager
2016-08-25 18:54:09.746884598 +0000 UTC [DEBUG pid=1088 pod='89851f65-fd69-4e10-94ee-4cc5b4f3dc3e' source='pod_operations.go:145'] Setting up stager manifest
2016-08-25 18:54:09.782062979 +0000 UTC [DEBUG pid=1088 pod='89851f65-fd69-4e10-94ee-4cc5b4f3dc3e' source='pod_operations.go:163'] Done up stager manifest
2016-08-25 18:54:09.782084785 +0000 UTC [DEBUG pid=1088 pod='89851f65-fd69-4e10-94ee-4cc5b4f3dc3e' source='pod_operations.go:268'] Starting pod stager.
2016-08-25 18:54:10.469005221 +0000 UTC [TRACE pid=1088 pod='89851f65-fd69-4e10-94ee-4cc5b4f3dc3e' source='pod_operations.go:349'] Launched stager process, pid: 1094
2016-08-25 18:54:16.466826042 +0000 UTC [INFO pid=1088 pod='' source='runner.go:61'] Received terminated. Shutting down.
2016-08-25 18:54:16.466853935 +0000 UTC [TRACE pid=1088 pod='89851f65-fd69-4e10-94ee-4cc5b4f3dc3e' source='pod_operations.go:399'] Sending shutdown signal to the stager process
2016-08-25 18:54:16.466893653 +0000 UTC [DEBUG pid=1088 pod='89851f65-fd69-4e10-94ee-4cc5b4f3dc3e' source='pod_operations.go:375'] Pod is shutting down, not ready signal
2016-08-25 18:54:16.466907388 +0000 UTC [TRACE pid=1088 pod='89851f65-fd69-4e10-94ee-4cc5b4f3dc3e' source='manager.go:138'] Network pod provisioned and running
2016-08-25 18:54:16.467124317 +0000 UTC [DEBUG pid=1088 pod='' source='server.go:89'] Server is ready
2016-08-25 18:54:16.467136396 +0000 UTC [INFO pid=1088 pod='' source='runner.go:273'] kurmad now ready at path unix:///tmp/d20160825-1082-qoeftf/kurma.sock
2016-08-25 18:54:16.467952723 +0000 UTC [WARN pid=1088 pod='89851f65-fd69-4e10-94ee-4cc5b4f3dc3e' source='utils.go:256'] Stager process has exited: exit status 0
2016-08-25 18:54:16.467969931 +0000 UTC [TRACE pid=1088 pod='89851f65-fd69-4e10-94ee-4cc5b4f3dc3e' source='pod_operations.go:406'] Stager has exited
2016-08-25 18:54:16.467977151 +0000 UTC [TRACE pid=1088 pod='89851f65-fd69-4e10-94ee-4cc5b4f3dc3e' source='pod_operations.go:440'] Tearing down stager container.
2016-08-25 18:54:16.513255895 +0000 UTC [DEBUG pid=1088 pod='89851f65-fd69-4e10-94ee-4cc5b4f3dc3e' source='pod_operations.go:302'] Stager: Stopping stagers debug logs output
time="2016-08-25T18:54:16Z" level=warning msg="wait: no child processes" 
2016-08-25 18:54:16.585151794 +0000 UTC [TRACE pid=1088 pod='89851f65-fd69-4e10-94ee-4cc5b4f3dc3e' source='pod_operations.go:450'] Done tearing down stager container.
2016-08-25 18:54:16.585168155 +0000 UTC [TRACE pid=1088 pod='89851f65-fd69-4e10-94ee-4cc5b4f3dc3e' source='pod_operations.go:461'] Removing container directories.
2016-08-25 18:54:16.588070020 +0000 UTC [TRACE pid=1088 pod='89851f65-fd69-4e10-94ee-4cc5b4f3dc3e' source='pod_operations.go:475'] Done tearing down container directories.
2016-08-25 18:54:16.588267009 +0000 UTC [TRACE pid=1088 pod='89851f65-fd69-4e10-94ee-4cc5b4f3dc3e' source='pod_operations.go:482'] Removing from the Pod Manager.
Shutdown complete, exiting
```

It looks like the networking pod hung on startup when it shouldn't have. Don't see its stager logs though, may need to verify debug is on then or something.
